"use client";
import { useState } from "react";
import type { DashboardData, StudentProfile } from "@/lib/types";

const field = (label:string, value?: string) => <div className="profile-item"><b>{label}</b>{value || "Not specified"}</div>;
export function Dashboard({ initialData }: { initialData: DashboardData }) {
  const [data, setData] = useState(initialData); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function upload(file?: File) { if (!file) return; setBusy(true); setMessage("Extracting your profile…"); const form=new FormData(); form.append("resume",file); const r=await fetch("/api/resume",{method:"POST",body:form}); const body=await r.json(); setBusy(false); if(!r.ok){setMessage(body.error||"Could not process that file.");return;} setData(x=>({...x,profile:body.profile}));setMessage("Profile extracted. You can now find matching jobs."); }
  async function findJobs(){ setBusy(true);setMessage("Collecting and ranking fresh jobs through Apify…");const r=await fetch("/api/jobs/refresh",{method:"POST"});const body=await r.json();setBusy(false);if(!r.ok){setMessage(body.error||"Could not refresh jobs.");return;}setData(body);setMessage(`Updated ${body.jobs.length} ranked jobs.`); }
  const p: StudentProfile|undefined=data.profile;
  return <main><header className="header"><div><div className="eyebrow">Personal AI job dashboard</div><h1>10x Job Hunter</h1><p>Find jobs that match your resume.</p></div><div className="status">Last updated: {data.lastUpdated ? new Date(data.lastUpdated).toLocaleString() : "Not yet"}</div></header>
  <div className="top-grid"><section className="panel"><h2>1. Upload your resume</h2><div className="upload"><p>PDF or DOCX — your file is used only to build this profile.</p><label>{busy?"Working…":"Choose resume"}<input disabled={busy} type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>upload(e.target.files?.[0])}/></label></div></section>
  <section className="panel"><h2>2. Extracted student profile</h2>{p?<><div className="profile-grid">{field("Preferred roles",p.preferredRoles.join(", "))}{field("Experience level",p.experienceLevel)}{field("Location",p.locationPreference)}{field("Work preference",p.workPreference)}{field("Education",p.education)}</div><p><b>Skills</b></p><div className="chips">{p.skills.length?p.skills.map(s=><span className="chip" key={s}>{s}</span>):"No skills identified"}</div></>:<p>Upload a resume to see your skills, preferences, education and experience.</p>}</section></div>
  <div className="controls"><button className="primary" disabled={!p||busy} onClick={findJobs}>{busy?"Working…":"Find My Jobs"}</button>{message&&<span className={message.includes("missing")||message.includes("Could not")?"notice":"status"}>{message}</span>}</div>
  <section><h2>3. Ranked jobs</h2>{data.jobs.length?<div className="job-list">{data.jobs.map(j=><article className="panel job" key={j.id}><div className="score">{j.matchScore}%</div><div><h3>{j.title}</h3><div className="meta"><span>{j.company||"Company unavailable"}</span><span>•</span><span>{j.location||"Location unavailable"}</span><span>•</span><span>{j.source}</span>{j.postedDate&&<><span>•</span><span>{j.postedDate}</span></>}</div><div className="chips" style={{marginTop:9}}>{j.matchingSkills.map(s=><span className="chip" key={s}>✓ {s}</span>)}</div><p className="description">{j.description.slice(0,220)}{j.description.length>220?"…":""}</p></div><a className="apply" href={j.jobUrl} target="_blank" rel="noopener noreferrer">Apply ↗</a></article>)}</div>:<div className="empty"><p>{p?"No jobs yet. Use Find My Jobs to fetch the latest results.":"Your best matches will appear here after you upload a resume."}</p></div>}</section></main>;
}
