import crypto from "crypto"; import type { Job, StudentProfile } from "./types";
const str=(x:unknown)=>typeof x==="string"?x:"";const list=(x:unknown)=>Array.isArray(x)?x.map(str).filter(Boolean):str(x).split(/[,|•]/).map(x=>x.trim()).filter(Boolean);
export function normalize(raw:Record<string,unknown>, source:string):Job|undefined{const jobUrl=str(raw.job_url||raw.jobUrl||raw.url||raw.applyUrl||raw.link);const title=str(raw.title||raw.jobTitle||raw.position);if(!title||!jobUrl)return;const company=str(raw.company||raw.companyName||raw.employer);const location=str(raw.location||raw.jobLocation);const id=crypto.createHash("sha256").update(jobUrl||`${company}|${title}|${location}|${source}`).digest("hex");return{id,title,company,location,jobUrl,source:str(raw.source)||source,postedDate:str(raw.posted_date||raw.postedDate||raw.datePosted),description:str(raw.description||raw.jobDescription||raw.text),requiredSkills:list(raw.required_skills||raw.requiredSkills||raw.skills),employmentType:str(raw.employment_type||raw.employmentType||raw.type),remoteType:str(raw.remote_type||raw.remoteType||raw.workplaceType),salary:str(raw.salary||raw.salaryRange),matchScore:0,matchingSkills:[]};}
export function dedupe(jobs:Job[]){return [...new Map(jobs.map(j=>[j.jobUrl||`${j.company}|${j.title}|${j.location}|${j.source}`,j])).values()];}
export function scoreJob(job:Job, profile:StudentProfile):Job {const hay=`${job.title} ${job.description} ${job.requiredSkills.join(" ")}`.toLowerCase();const matches=profile.skills.filter(s=>hay.includes(s.toLowerCase()));let score=Math.min(60,matches.length*12);if(profile.preferredRoles.some(r=>hay.includes(r.toLowerCase())))score+=18;if(profile.workPreference&&`${job.remoteType} ${job.location}`.toLowerCase().includes(profile.workPreference.toLowerCase()))score+=10;if(profile.locationPreference&&job.location.toLowerCase().includes(profile.locationPreference.toLowerCase()))score+=8;if(profile.experienceLevel.toLowerCase().includes("intern")&&/intern|student|graduate/.test(hay))score+=10;return {...job,matchScore:Math.min(100,score),matchingSkills:matches.slice(0,5)};}
function actorInput(profile:StudentProfile) {
  let overrides: Record<string, unknown> = {};
  if (process.env.APIFY_ACTOR_INPUT) {
    try { overrides = JSON.parse(process.env.APIFY_ACTOR_INPUT) as Record<string, unknown>; }
    catch { throw new Error("APIFY_ACTOR_INPUT must be valid JSON."); }
  }
  const keywords = profile.preferredRoles[0] || profile.skills.slice(0, 3).join(" ");
  if (!keywords && !overrides.keywords) throw new Error("No job keywords could be derived from the resume. Add APIFY_ACTOR_INPUT={\"keywords\":\"your target role\"} to .env.local.");
  return { keywords, ...overrides };
}
export async function collectAndScore(profile:StudentProfile){const token=process.env.APIFY_API_TOKEN, actors=process.env.APIFY_ACTOR_IDS?.split(",").map(x=>x.trim()).filter(Boolean);if(!token||!actors?.length)throw new Error("Apify is not configured. Add APIFY_API_TOKEN and permitted APIFY_ACTOR_IDS to .env.local.");const input=actorInput(profile);const all:Job[]=[];const failures:string[]=[];for(const actor of actors){const url=`https://api.apify.com/v2/acts/${encodeURIComponent(actor)}/run-sync-get-dataset-items?token=${encodeURIComponent(token)}`;const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});if(!response.ok){failures.push(`${actor} (${response.status})`);continue;}const items=await response.json() as Record<string,unknown>[];items.forEach(x=>{const j=normalize(x,actor);if(j)all.push(j);});}if(!all.length&&failures.length===actors.length)throw new Error(`Apify actor request failed: ${failures.join(", ")}. Check the actor input settings in .env.local.`);return dedupe(all).map(j=>scoreJob(j,profile)).sort((a,b)=>b.matchScore-a.matchScore);}
